name: lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint/Format check
    steps:
      - uses: actions/checkout@v3
      - name: install node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: install
        run: npm install
      - name: lint *.js
        run: npm run eslint
      - name: format code
        run: npm run prettier-check
